export const WALRUS_CONFIG = {
  PUBLISHERS: [
    "https://publisher.walrus-testnet.walrus.space",
    "https://wal-publisher-testnet.staketab.org",
    "https://walrus-testnet-publisher.bartestnet.com",
    "https://walrus-testnet-publisher.nodeinfra.com",
    "https://walrus-testnet.stakingdefenseleague.com",
    "https://walrus.testnet.pops.one",
    "https://sui-walrus-testnet.bwarelabs.com/publisher",
    "https://walrus-publish-testnet.chainode.tech:9003",
    "https://testnet-publisher.walrus.space",
    "https://walrus-testnet-publisher.redundex.com",
  ],
  AGGREGATORS: [
    "https://aggregator.walrus-testnet.walrus.space",
    "https://wal-aggregator-testnet.staketab.org",
    "https://walrus-testnet-aggregator.bartestnet.com",
    "https://walrus-testnet-aggregator.nodeinfra.com",
    "https://walrus-tn.juicystake.io:9443",
    "https://walrus-agg.testnet.pops.one",
    "https://sui-walrus-testnet.bwarelabs.com/aggregator",
    "https://walrus-testnet.chainode.tech:9002",
    "https://testnet-aggregator.walrus.space",
    "https://walrus-testnet-aggregator.redundex.com",
  ],

  DEFAULT_EPOCHS: 5,
  MAX_FILE_SIZE_MB: 10,
  SUPPORTED_MIME_TYPES: [
    "text/plain",
    "text/markdown",
    "application/json",
    "image/png",
    "image/jpeg",
    "image/gif",
    "application/pdf",
  ],
};
